clone_folder: c:\projects\nurbs

os:
  - Visual Studio 2017
  - Visual Studio 2017 Preview

platform:
  - Win32
  - x64

build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

test_script:
- ctest -V -C Debug