# enable trusty
dist: trusty
sudo: required
# c++
language: cpp
# new stuff is good stuff
# test on clang and gcc

matrix:
  include:
    # linux g++7
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER=g++-7
    
    # osx g++7
    - os: osx
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER=g++-7

    # osx clang-5.0
    - os: osx
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env: COMPILER=clang++-5.0

# lets go
script:
  - $COMPILER --version
  - mkdir build
  - cd build 
  - cmake .. -DCMAKE_CXX_COMPILER=$COMPILER
  - cmake --build .
  - ctest -V