# enable trusty
dist: trusty
sudo: required
# c++
language: cpp
# new stuff is good stuff
# test on clang and gcc

matrix:
  include:
    # linux g++7
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER=g++-7
    
    # osx g++
    - os: osx
      osx_image: xcode9.1
      compiler: gcc
      env: COMPILER=g++

    # osx clang
    - os: osx
      osx_image: xcode9.1
      compiler: clang
      env: COMPILER=clang++

# lets go
script:
  - $COMPILER --version
  - mkdir build
  - cd build 
  - cmake .. -DCMAKE_CXX_COMPILER=$COMPILER
  - cmake --build .
  - ctest -V